/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        red12: "#D43B3B1F",
        red100: "#D43B3B",
        green12: "#519B2F1F",
        greenGrid: "#519B2F",
        greenPrimary: "#333E40",
        borderGreen: "#63A941A6",
        black: "#000000",
        tabActive: "#9500FF",
        purpleCalm: "#5E4980",
        white: "#FFFFFF",
        primaryGray: "#646464",
        secondaryGray: "#D9D9D9",
        purple84: "#3E2B5CD6",
        purple100: "#3E2B5C",
        lightOrange: "#FFE6C580",
        orange: "#FFD195",
        purple50: "#3E2B5C80",
        whitebg: "#F6F6F6",
        yellowStarCard: "#FFFAC1",
        yellowStarCardBorder: "#FFDE59",
        greenSecondary: "#84D55D",
        orangeSequenceCard: "#FFE6C580",
        orangeSequenceCardBorder: "#FFD195",
        greenBubble: "#E2EBDE",
        purplePrice: "#9969EB",
        featureGray: "#EBEBEB",
        progressSubjectCardBg: "#F7F7F7",

        // FRONT-06.5 - Meu Progresso
        cardBorder: "#F1F1F1",
        progressTrack: "#D9D9D9",
        progressPurple: "#9500FF",
        simuladoProgress: "#B879D8",

        metricsYellowBg: "#FFFCE6",
        metricsOrangeBg: "#FEF3EA",
        starIcon: "#F6D800",
        flameIcon: "#F04444",

        accuracyPurpleDark: "#5B3794",
        accuracyPurpleMuted: "#6B4E79",
        accuracyPurpleLight: "#A185D1",
      },
      fontFamily: {
        poppins: ["Poppins-Regular"],
        "poppins-semi": ["Poppins-SemiBold"],
        "poppins-bold": ["Poppins-Bold"],
        inter: ["Inter-Regular"],
        "inter-semi": ["Inter-SemiBold"],
        "inter-medium": ["Inter-Medium"],
      },
    },
  },
  plugins: [],
};