/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        red12: "#D43B3B1F",
        red100: "#D43B3B",
        green12: "#519B2F1F",
        greenGrid: "#519B2F",
        greenPrimary: "#333E40",
        black: "#000000",
        tabActive: "#9500FF",
        purpleCalm: "#5E4980",
        white: "#FFFFFF",
        primaryGray: "#646464",
        secondaryGray: "#D9D9D9",
        purple84: "#3E2B5CD6",
        purple100: "#3E2B5C",
        lightOrange: "#FFE6C580",
        orange: "#FFD195",
        purple50: "#3E2B5C80",
        whitebg: "#F6F6F6",
        yellowStarCard: "#FFFAC1",
        yellowStarCardBorder: "#FFDE59",
        greenSecondary: "#84D55D",
        orangeSequenceCard: "#FFE6C580",
        orangeSequenceCardBorder: "#FFD195",
        greenBubble: "#E2EBDE",
        purplePrice: "#9969EB",
        featureGray: "#EBEBEB",
      },
      fontFamily: {
        poppins: ["Poppins-Regular"],
        "poppins-semi": ["Poppins-SemiBold"],
        "poppins-bold": ["Poppins-Bold"],
        inter: ["Inter-Regular"],
        "inter-semi": ["Inter-SemiBold"],
        "inter-medium": ["Inter-Medium"],
      },
    },
  },
  plugins: [],
};
