#!/bin/bash

# Pega a mensagem digitada
commit_msg=$(cat "$1")

# Regex: tipo(id_clickup): mensagem
regex="^(feature|fix|hotfix|chore|refactor|arch|docs|test)\([a-zA-Z0-9]+\):\s.{5,}$"

if [[ ! $commit_msg =~ $regex ]]; then
  echo -e "\n[ERRO DE PADRONIZAÇÃO]"
  echo -e "Sua mensagem de commit não segue as regras do projeto."
  echo -e "--------------------------------------------------------"
  echo -e "Correto: feature(86ag34u4q): add suporte a dark mode"
  echo -e "Seu commit: $commit_msg"
  echo -e "--------------------------------------------------------"
  echo -e "Tipos: feature, fix, hotfix, chore, refactor, arch, docs, test"
  echo -e "ID ClickUp deve estar entre parênteses e ter um espaço após os dois pontos.\n"
  exit 1
fi